name: CI - Bazel GPU tests (RBE)

on:
  pull_request:
      branches:
        - main
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    if: github.event.repository.fork == false
    strategy:
      matrix:
        runner: ["linux-x86-g2-16-l4-1gpu"]

    runs-on: ${{ matrix.runner }}
    container: 'us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build:latest'

    env:
      JAXCI_HERMETIC_PYTHON_VERSION: "3.12"

    steps:
      - uses: actions/checkout@v3
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@main
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      - name: Run Bazel GPU Tests with RBE
        run: ./ci/run_bazel_test.sh "ci/envs/run_tests/bazel_gpu_rbe.env"